name: flutter_camera

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  build:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.