// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum FlashState: Int {
  /// Flash state disabled
  case disabled = 0
  /// Flash state enabled
  case enabled = 1
}

private class CameraApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FlashState(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CameraApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FlashState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class CameraApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CameraApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CameraApiPigeonCodecWriter(data: data)
  }
}

class CameraApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CameraApiPigeonCodec(readerWriter: CameraApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraApi {
  func dispose() throws
  func initialize(flashState: FlashState, flashTorchLevel: Double) throws
  func takePicture(completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func setZoomLevel(zoomLevel: Double) throws
  func getCurrentZoomLevel() throws -> Double
  func getMinimumZoomLevel() throws -> Double
  func getMaximumZoomLevel() throws -> Double
  func setFlashStatus(isActive: Bool) throws
  func getFlashStatus() throws -> Bool
  func getPlatformVersion() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraApiSetup {
  static var codec: FlutterStandardMessageCodec { CameraApiPigeonCodec.shared }
  /// Sets up an instance of `CameraApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let flashStateArg = args[0] as! FlashState
        let flashTorchLevelArg = args[1] as! Double
        do {
          try api.initialize(flashState: flashStateArg, flashTorchLevel: flashTorchLevelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let takePictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.takePicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePictureChannel.setMessageHandler { _, reply in
        api.takePicture { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takePictureChannel.setMessageHandler(nil)
    }
    let setZoomLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.setZoomLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setZoomLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let zoomLevelArg = args[0] as! Double
        do {
          try api.setZoomLevel(zoomLevel: zoomLevelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setZoomLevelChannel.setMessageHandler(nil)
    }
    let getCurrentZoomLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.getCurrentZoomLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentZoomLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCurrentZoomLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCurrentZoomLevelChannel.setMessageHandler(nil)
    }
    let getMinimumZoomLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.getMinimumZoomLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMinimumZoomLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMinimumZoomLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMinimumZoomLevelChannel.setMessageHandler(nil)
    }
    let getMaximumZoomLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.getMaximumZoomLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMaximumZoomLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMaximumZoomLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMaximumZoomLevelChannel.setMessageHandler(nil)
    }
    let setFlashStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.setFlashStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFlashStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isActiveArg = args[0] as! Bool
        do {
          try api.setFlashStatus(isActive: isActiveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFlashStatusChannel.setMessageHandler(nil)
    }
    let getFlashStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.getFlashStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFlashStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFlashStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFlashStatusChannel.setMessageHandler(nil)
    }
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlatformVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CameraImageListenerProtocol {
  func onImageAvailable(image imageArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onQrCodeAvailable(qrCode qrCodeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class CameraImageListener: CameraImageListenerProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CameraApiPigeonCodec {
    return CameraApiPigeonCodec.shared
  }
  func onImageAvailable(image imageArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraImageListener.onImageAvailable\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([imageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onQrCodeAvailable(qrCode qrCodeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.native_camera_controller_platform_interface.CameraImageListener.onQrCodeAvailable\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([qrCodeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
